FROM python:3.9-slim

WORKDIR /app

COPY requirements-router.txt .

RUN pip install --no-cache-dir -r requirements-router.txt

COPY . .

EXPOSE 8080

# Lệnh để chạy ứng dụng router khi container khởi động
CMD ["uvicorn", "router:app", "--host", "0.0.0.0", "--port", "8080"]
